#!/bin/sh
#
#  This file is part of systemd.
#
#  Copyright (C) 2020 Jolla Ltd.
#  Contact: Franz-Josef Haider <franz.haider@jolla.com>
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
#  systemd is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with systemd; If not, see <http://www.gnu.org/licenses/>.
#  ------------------------
#
# This is helper script that can be used to run systemctl commands on user 
# session when logged in as root
# It searches for the active user session and runs the command for that user
# Usage:
# systemctl-user <any systemctl command with parameters>
# example:
# systemctl-user stop myapp.service

USER_ID=$(id -u $(loginctl list-sessions | grep seat0 | tr -s " " | cut -d " " -f 4))
#export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$USER_ID/dbus/user_bus_socket"
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$USER_ID/bus"

systemctl --user $@
